export const PETS_IMAGES:any = {
    1: "assets/pictures/dog1.jpg",
    2: "assets/pictures/dog2.jpg",
    3: "assets/pictures/dog3.jpg",
    4: "assets/pictures/dog4.jpg",
    5: "assets/pictures/dog5.jpg",
    6: "assets/pictures/dog6.jpg",
    10: "assets/pictures/dog7.jpg",
    17: "assets/pictures/dog8.jpg",
    24: "assets/pictures/dog9.jpg",
    31: "assets/pictures/dog10.jpg",
    38: "assets/pictures/dog11.jpg",
    45: "assets/pictures/dog12.jpg",
    52: "assets/pictures/dog13.jpg",
    59: "assets/pictures/dog14.jpg",
    66: "assets/pictures/dog15.jpg",
    73: "assets/pictures/dog16.jpg",
    80: "assets/pictures/dog17.jpg",
    87: "assets/pictures/dog18.jpg",
    94: "assets/pictures/dog19.jpg",
    101: "assets/pictures/dog20.jpg",
    108: "assets/pictures/dog21.jpg",
    115: "assets/pictures/dog22.jpg",
    122: "assets/pictures/dog23.jpg",
    129: "assets/pictures/dog24.jpg",
    136: "assets/pictures/dog25.jpg",
    143: "assets/pictures/dog26.jpg",
    150: "assets/pictures/dog27.jpg",
}


export const NO_IMAGE = "assets/pictures/dog-default.jpg";